### ISSUE TITLE
Please Stop this Script

### ISSUE THREAD

**Issue by atiqsamtia** [HollowMan6/Tool-Set-for-Github-Follow#1]
Please stop this script. You already have 88K Followings and you are breaking everyone's Github Feed

![image](https://user-images.githubusercontent.com/5112753/80723574-3c948b80-8b1a-11ea-9d5f-0a336797eada.png)

**Comment by HollowMan6** [comment]
Ok, I'll stop this. sorry for the bad experience, I didn't realize it can cause troubles to others.

**Comment by leo-lb** [comment]
So that's how you followed me

**Comment by parthibx24** [comment]
Haha, same here xD

**Comment by pawamoy** [comment]
Besides, when someone starts following me, and I see that they follow 1K+ users, I never follow back, because they clearly follow just to follow (and get followed back). It's a no-thanks for me! :slightly_smiling_face:
